In [7]:
import numpy as np

from benches.parallel import main

result = main('results/environ/all/mappo/check/run1/models/actor.pt')

In [12]:
crashes = np.mean(result[:, :, 0], axis=2)
steps = np.median(result[:, :, 1], axis=2)
dones = np.mean(result[:, :, 2], axis=2)

In [13]:
crashes

array([[0.  , 0.17, 0.17, 0.19, 0.19, 0.16, 0.14],
       [0.18, 0.51, 0.61, 0.39, 0.28, 0.33, 0.36],
       [0.2 , 0.65, 0.53, 0.53, 0.49, 0.46, 0.5 ],
       [0.56, 0.8 , 0.82, 0.79, 0.91, 0.65, 0.77],
       [0.89, 0.83, 1.27, 1.04, 0.77, 0.99, 1.14],
       [0.94, 1.21, 1.47, 1.41, 1.49, 1.39, 1.16],
       [1.48, 1.62, 1.68, 1.63, 1.61, 1.56, 1.66]])

In [14]:
steps

array([[ 16. ,  16. ,  17. ,  23. ,  33. ,  60.5,  76.5],
       [ 41.5,  39. ,  41.5,  62. ,  69.5, 103.5, 110.5],
       [ 65.5,  63.5,  89. , 112. , 115. , 141. , 152. ],
       [ 88. ,  93. , 123.5, 137. , 161. , 193. , 218. ],
       [121.5, 133. , 145. , 164. , 213.5, 207. , 225. ],
       [156.5, 167. , 195.5, 220.5, 234.5, 248.5, 270.5],
       [200.5, 196. , 214.5, 247.5, 261.5, 272.5, 268. ]])

In [15]:
dones

array([[1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  ],
       [1.  , 1.  , 1.  , 1.  , 1.  , 1.  , 1.  ],
       [1.  , 1.  , 1.  , 0.99, 0.99, 1.  , 1.  ],
       [1.  , 1.  , 1.  , 1.  , 0.98, 1.  , 1.  ],
       [0.99, 1.  , 1.  , 1.  , 0.99, 1.  , 0.96],
       [0.99, 1.  , 1.  , 0.99, 0.99, 0.99, 0.98],
       [0.99, 1.  , 1.  , 0.98, 0.99, 0.98, 0.97]])